#!/bin/bash

SEC=$(date +%Y%m%d%H%M%S)
export SEC

quietly () {
  local cmd="$(shift)"
  echo "==>$cmd $@"
  if [ "$VERBOSE" -eq "1" ]; then
    $cmd $@
  else
    set +e
    $cmd $@ >"${HSVM_ROOT}/log/build-${SEC}-out.log" 2>"${HSVM_ROOT}/log/build-${SEC}-error.log"
    if [ "$?" -ne "0" ]; then
      tail -20 "${HSVM_ROOT}/log/build-${SEC}-error.log"
      exit 1
    fi
    set -e
  fi
}
