#!/bin/bash

SEC=$(date +%Y%m%d%H%M%S)
export SEC

quietly () {
  local cmd="$(shift)"
  echo "==>$cmd $@"
  if [ "$VERBOSE" -eq "1" ]; then
    $cmd $@
  else
    set +e
    $cmd $@ >"${HSVM_ROOT}/log/build-${SEC}-out.log" 2>"${HSVM_ROOT}/log/build-${SEC}-error.log"
    if [ "$?" -ne "0" ]; then
      tail -20 "${HSVM_ROOT}/log/build-${SEC}-error.log"
      exit 1
    fi
    set -e
  fi
}

default_arch () {
  possibles=($(find "$GHCS_PATH" -name "$1"* -type d -exec basename {} \;))
  case "${#possibles[@]}" in
    1) echo "${possibles[0]}" ;;
    2)
      echo >&2 "hsvm: multiple architectures present for version \`$1'; try ${1}-i386 or ${1}-x86_64"
      exit 1
      ;;
    *) echo >&2 "hsvm: more than 2 arches for version \`$1' found, something is wrong"
      exit 1
      ;;
  esac
}
