#!/usr/bin/env bash
# Summary: Remove a GHC version
# Usage: hsvm rm version

set -e
[ -n "$HSVM_DEBUG" ] && set -x
source "$HSVM_LIB/_hsvm-functions"

if [ -z "$1" ]; then
  echo "usage: hsvm rm version" >&2
  exit 1
else
  ver="$(default_arch "$1")"
  if [ "$ver" = "$(hsvm current)" ]; then
    removing_current="yes"
  fi
  if [ -d "${GHCS_PATH}/$ver" ]; then
    rm -rf "${GHCS_PATH}/$ver"
    echo "hsvm: removed ghc-$ver"
    [ -n "$removing_current" ] && hsvm use "$(hsvm versions | tail -1)" 2>/dev/null
    true
  else
    echo "hsvm: no such version \`$ver'" >&2
    exit 1
  fi
fi

hsvm rehash
