#!/usr/bin/env bash
# Summary: Show the current used version of GHC
# Usage: hsvm current

set -e
[ -n "$HSVM_DEBUG" ] && set -x

if [ -f "${VERSION_FILE}" ]; then
  cat "${VERSION_FILE}"
else
  echo "hsvm: no version configured, try \`hsvm use'" >&2
  exit 1
fi
