#!/usr/bin/env bash
# Summary: Return completions for commands
# Usage: hsvm completions partial input

set -e
[ -n "$HSVM_DEBUG" ] && set -x

case "$1" in
install )
  echo "HEAD"
  cat "$(dirname "$0")/../versions"
  ;;
use | rm )
  for dir in "${GHCS_PATH}/"*; do
    echo "$(basename "$dir")"
  done
  ;;
esac
