#!/usr/bin/env bash
# Summary: Select a GHC version to use in the shell.
# Usage: hsvm use version

set -e
[ -n "$HSVM_DEBUG" ] && set -x
source "$HSVM_LIB/_hsvm-functions"

set_version() {
  ver="$(default_arch "$1")"
  if [ ! -d "${GHCS_PATH}/$ver" ]; then
    echo "hsvm: GHC $ver is not installed" >&2
    exit 1
  else
    echo "$ver" > "${VERSION_FILE}"
  fi
  hsvm rehash
}

if [ -n "$1" ]; then
  set_version "$1"
else
  echo "usage: hsvm use version" >&2
  exit 1
fi
