#!/usr/bin/env bash
# Summary: Show the current used version of GHC
# Usage: hsvm current

set -e
[ -n "$HSVM_DEBUG" ] && set -x

if [ -f "${HSVM_ROOT}/version" ]; then
  cat "${HSVM_ROOT}/version"
else
  echo "hsvm: no version configure, try \`hsvm use'" >&2
  exit 1
fi
