#!/usr/bin/env bash
# Summary: Show all GHC versions.
# Usage: hsvm shell version

set -e
[ -n "$HSVM_DEBUG" ] && set -x

[ -f "${HSVM_ROOT}/version" ] && CURRENT="$(<"${HSVM_ROOT}/version")"

while IFS= read -d $'\0' -r dir ; do
  d="$(basename "$dir")"
  [ "$d" = "ghcs" ] && continue;
  if [ "$d" = "$CURRENT" ]; then
    echo "$d (current)"
  else
    echo "$d"
  fi
done < <(find "${HSVM_ROOT}/ghcs" -maxdepth 1 -type d -print0)
