#!/usr/bin/env bash
# Summary: Select a GHC version to use in the shell.
# Usage: hsvm use version

set -e
[ -n "$HSVM_DEBUG" ] && set -x

set_version() {
  if [ ! -d "${HSVM_ROOT}/ghcs/$1" ]; then
    echo "hsvm: GHC $1 is not installed" >&2
    exit 1
  fi
  echo "$1" > "${HSVM_ROOT}/version"
  hsvm rehash
}

if [ -n "$1" ]; then
  set_version "$1"
else
  echo "usage: hsvm use version" >&2
  exit 1
fi
